# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main

pool:
  name: 'Default'
  vmImage: 'XcodeAgent'


steps:
- task: Xcode@5
  inputs:
      actions: 'build test'
      sdk: 'iphonesimulator'
      xcWorkspacePath: '**/*.xcodeproj'
      xcodeVersion: 'default'
      useXcpretty: false
      scheme: 'iOSHelloWorld'